name: Services
on: push

jobs:
  node-docker:
   runs-on: ubuntu-latest
   services:
     app:
       image: eliarms/nodejs-api
       ports:
          - 3001:3000
     mongo:
        image: mongo
        ports:
          - "27017:27017"
   steps:
     - name: Post a User
       run: "curl -X POST http://localhost:3001/api/users
       -H 'Content-Tyoe:application/json' -d '
       {\"username\":\"hello\",\"address\":\"eliarms\"}'"

     - name: Get Users
       run: curl  http://localhost:3001/api/users
      